/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package perpustakaan;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql,sql_op,sql_siswa,sql_guru,status;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        Koneksi DB = new Koneksi();
//        UserSession UserSession = new UserSession();
        DB.config();
        con = DB.con;
        stat = DB.stm;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        jLabel3.setMaximumSize(new java.awt.Dimension(24, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(24, 24));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 82, 34));

        txt_username.setBackground(new java.awt.Color(102, 102, 102));
        txt_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 237, 50));

        combo.setBackground(new java.awt.Color(102, 102, 102));
        combo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Siswa", "Operator", "Guru" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel2.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 237, -1));

        login.setBackground(new java.awt.Color(51, 102, 255));
        login.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/gambar/icons-login.png"))); // NOI18N
        login.setText("Sign In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 237, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/gambar/icons-user-login.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/gambar/icons8-key-30.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txt_password.setBackground(new java.awt.Color(102, 102, 102));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 240, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/gambar/icons-go-back.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
      
        String u_id_operator = null;
        String u_nis = null;
        String u_nama_operator = null;
        String u_nama_siswa = null;
        String u_nama_guru = null;
        String u_no_telp = null;       
        String u_username = null;
        String u_ttl = null;
        String u_last_login = null;
        String u_status_login = null;
        String u_siswa_status_login = null;
        String u_guru_status_login = null;
       
                
        try{
            
            if(txt_username.getText().isEmpty() || txt_password.getText().isEmpty() || combo.getSelectedIndex() == 0){
                
                    JOptionPane.showMessageDialog(null, "Silahkan periksa kembali, data tidak boleh kosong!!");
                   
            }
            
            else{
          
          sql_op = "SELECT * FROM operator WHERE username='"+txt_username.getText()+"' AND password='"+txt_password.getText()+"'";
          sql_siswa = "SELECT * FROM siswa WHERE nis='"+txt_username.getText()+"' AND password='"+txt_password.getText()+"'";
          sql_guru = "SELECT * FROM guru WHERE username='"+txt_username.getText()+"' AND password='"+txt_password.getText()+"'";
          
            switch(status){
                
                //CASE OPERATOR
                case "Operator":
                    try{
                         rs = stat.executeQuery(sql_op);
                        
                         if(rs.next()){
                              
                              if(txt_username.getText().equals(rs.getString("username")) && txt_password.getText().equals(rs.getString("password"))){

                u_id_operator = rs.getString("id_operator");
                u_nama_operator = rs.getString("nama");
                u_no_telp = rs.getString("no_telp");
                u_username = rs.getString("username");
                u_last_login = rs.getString("last_login");
                u_status_login = rs.getString("status_login");
             
                UserSession.setU_id_operator(u_id_operator);
                UserSession.setU_nama_operator(u_nama_operator);
                UserSession.setU_no_telp(u_no_telp);
                UserSession.setU_username(u_username);
                UserSession.setU_last_login(u_last_login);
                UserSession.setU_status_login(u_status_login);
                
                
                LocalDateTime myDateObj = LocalDateTime.now();
             
                DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

                String formattedDate = myDateObj.format(myFormatObj);
                int sta = 2;
                 String sql3 = "UPDATE operator SET status_login='"+sta+"', last_login='"+formattedDate+"' where id_operator='"+u_id_operator+"' ";
                        
                    stat.execute(sql3);
                   
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
                    new O_Dashboard().setVisible(true);
                    this.setVisible(false);
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
                         
                    }
                
                    catch(Exception e){
                       JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                   break;
                    //END CASE OPERATOR
                    
                    //CASE SISWA
                    case "Siswa":
                    try{
                         rs = stat.executeQuery(sql_siswa);
                       
                         if(rs.next()){
                            
                if(txt_username.getText().equals(rs.getString("nis")) && txt_password.getText().equals(rs.getString("password"))){
                    
                    u_nis = rs.getString("nis");
                    u_nama_siswa = rs.getString("nama");
                    u_ttl = rs.getString("ttl");
                    u_no_telp = rs.getString("no_telp");
                    u_last_login = rs.getString("last_login");
                    u_siswa_status_login = "2"; 
                
                   
                    
                        LocalDateTime myDateObj = LocalDateTime.now();
             
                        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

                        String formattedDate = myDateObj.format(myFormatObj);
                        int sta = 2;
                        String sql4 = "UPDATE siswa SET status_login='"+sta+"', last_login='"+formattedDate+"' where nis='"+u_nis+"' ";
                        stat.execute(sql4);
                    
                    UserSession.setU_nis(u_nis);
                    UserSession.setU_nama_siswa(u_nama_siswa);
                    UserSession.setU_ttl(u_ttl);
                    UserSession.setU_no_telp(u_no_telp);
                    UserSession.setU_last_login(u_last_login);
                    UserSession.setU_siswa_status_login(u_siswa_status_login);
                    
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
//                    System.out.println(u_siswa_status_login);
                    new P_Dashboard().setVisible(true);
                    this.setVisible(false);
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
                         
                    }
                
                    catch(Exception e){
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                   break;
                        
                   //END CASE SISWA     
                   
                   //CASE GURU
                        case "Guru":
                    try{
                         rs = stat.executeQuery(sql_guru);
                       
                         if(rs.next()){
                            
                if(txt_username.getText().equals(rs.getString("username")) && txt_password.getText().equals(rs.getString("password"))){
                    
                u_username = rs.getString("username");
                u_nama_guru = rs.getString("nama");
                u_ttl = rs.getString("ttl");
                u_no_telp = rs.getString("no_telp");
                u_last_login = rs.getString("last_login");
                u_guru_status_login =  "2"; 
                
                
                    UserSession.setU_username(u_username);
                    UserSession.setU_nama_guru(u_nama_guru);
                    UserSession.setU_ttl(u_ttl);
                    UserSession.setU_no_telp(u_no_telp);
                    UserSession.setU_last_login(u_last_login);
                    UserSession.setU_guru_status_login(u_guru_status_login);
                    
                        LocalDateTime myDateObj = LocalDateTime.now();
                        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                        String formattedDate = myDateObj.format(myFormatObj);
                        int sta = 2;
                        String sql4 = "UPDATE guru SET status_login='"+sta+"', last_login='"+formattedDate+"' where username='"+u_username+"' ";
                        stat.execute(sql4);
                    
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
                    new P_Transaksi().setVisible(true);
                    this.setVisible(false);
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
                         
                    }
                
                    catch(Exception e){
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                   break;
                        
                        
                  default:
                   JOptionPane.showMessageDialog(null, "Periksa Kembali");
            }
          
      }
        }
      catch(Exception e){
                       JOptionPane.showMessageDialog(null, e);
                    }
      
    }//GEN-LAST:event_loginActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
       if (combo.getSelectedIndex() == 0){
           status = "pilih";
       }
       else if (combo.getSelectedIndex() == 1){
           status = "Siswa";
       }
        else if (combo.getSelectedIndex() == 2){
           status = "Operator";
       }
       
        else if (combo.getSelectedIndex() == 3){
           status = "Guru";
       }
    }//GEN-LAST:event_comboActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         new Menu_Utama().setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
